// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRvuMMnD6V17gZsv0YrSrDPusrgiy8jVA',
    appId: '1:1024540748358:web:c179de177d017bd5d47847',
    messagingSenderId: '1024540748358',
    projectId: 'newsfeedapp-f6868',
    authDomain: 'newsfeedapp-f6868.firebaseapp.com',
    storageBucket: 'newsfeedapp-f6868.appspot.com',
    measurementId: 'G-QT382WDCTY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB34ng0BnD7KH5jIZ1np_ReYGSUjsRGuBM',
    appId: '1:1024540748358:android:9750288d5552867fd47847',
    messagingSenderId: '1024540748358',
    projectId: 'newsfeedapp-f6868',
    storageBucket: 'newsfeedapp-f6868.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYoh0CDgCaEHK0YITEhJc8wR6a8w7g7E0',
    appId: '1:1024540748358:ios:0762172e42888905d47847',
    messagingSenderId: '1024540748358',
    projectId: 'newsfeedapp-f6868',
    storageBucket: 'newsfeedapp-f6868.appspot.com',
    iosBundleId: 'com.example.newsfeedapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYoh0CDgCaEHK0YITEhJc8wR6a8w7g7E0',
    appId: '1:1024540748358:ios:0762172e42888905d47847',
    messagingSenderId: '1024540748358',
    projectId: 'newsfeedapp-f6868',
    storageBucket: 'newsfeedapp-f6868.appspot.com',
    iosBundleId: 'com.example.newsfeedapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRvuMMnD6V17gZsv0YrSrDPusrgiy8jVA',
    appId: '1:1024540748358:web:599125d62df4252bd47847',
    messagingSenderId: '1024540748358',
    projectId: 'newsfeedapp-f6868',
    authDomain: 'newsfeedapp-f6868.firebaseapp.com',
    storageBucket: 'newsfeedapp-f6868.appspot.com',
    measurementId: 'G-4VY80W42PG',
  );
}
